// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8jx6EB-d8K4C_J1vaXD5eyXJ9O_Ojfn4',
    appId: '1:118664153927:web:34ae257c4897fe91ff9a62',
    messagingSenderId: '118664153927',
    projectId: 'recipe-app-a9521',
    authDomain: 'recipe-app-a9521.firebaseapp.com',
    storageBucket: 'recipe-app-a9521.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrBYG2ltaUV061PWOR39NdmNJH2Yx0pdA',
    appId: '1:118664153927:android:0744c9842824bd6fff9a62',
    messagingSenderId: '118664153927',
    projectId: 'recipe-app-a9521',
    storageBucket: 'recipe-app-a9521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5dDztaNuJp2KWqhB4ZwYsPkYQ0P-sg7c',
    appId: '1:118664153927:ios:d26ae45fc542c2abff9a62',
    messagingSenderId: '118664153927',
    projectId: 'recipe-app-a9521',
    storageBucket: 'recipe-app-a9521.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5dDztaNuJp2KWqhB4ZwYsPkYQ0P-sg7c',
    appId: '1:118664153927:ios:d26ae45fc542c2abff9a62',
    messagingSenderId: '118664153927',
    projectId: 'recipe-app-a9521',
    storageBucket: 'recipe-app-a9521.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8jx6EB-d8K4C_J1vaXD5eyXJ9O_Ojfn4',
    appId: '1:118664153927:web:3902163273270df3ff9a62',
    messagingSenderId: '118664153927',
    projectId: 'recipe-app-a9521',
    authDomain: 'recipe-app-a9521.firebaseapp.com',
    storageBucket: 'recipe-app-a9521.firebasestorage.app',
  );
}
